name: Deploy to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}   # 👈 este faltaba
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/frontend:latest ./front_despacho
          docker push ${{ steps.login-ecr.outputs.registry }}/frontend:latest

      - name: Build and push back-despachos
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/back-despachos:latest ./back-Despachos_SpringBoot
          docker push ${{ steps.login-ecr.outputs.registry }}/back-despachos:latest

      - name: Build and push back-ventas
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/back-ventas:latest ./back-Ventas_SpringBoot
          docker push ${{ steps.login-ecr.outputs.registry }}/back-ventas:latest

